// Class: ReadBDTG_MaxDepth2
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG_MaxDepth2
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/21       [336405]
Creator        : fmeier
Date           : Tue Jun 30 19:13:56 2015
Host           : Linux lcgapp-slc6-physical1.cern.ch 2.6.32-431.29.2.el6.x86_64 #1 SMP Wed Sep 10 11:13:12 CEST 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/fmeier/git/b02dd/run
Training events: 45386
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
NTrees: "200" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "4" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "40" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "3.000000e-01" [Learning rate for GradBoost algorithm]
BaggedSampleFraction: "7.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
NegWeightTreatment: "ignorenegweightsintraining" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "7.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 13
varDTFChi2ndof_log            varDTFChi2ndof_log            varDTFChi2ndof_log            varDTFChi2ndof_log                                              'F'    [-2.65221524239,2.24187445641]
varIPChi2_log                 varIPChi2_log                 varIPChi2_log                 varIPChi2_log                                                   'F'    [-12.5979061127,3.09235835075]
varBDIRAOwnPV                 varBDIRAOwnPV                 varBDIRAOwnPV                 varBDIRAOwnPV                                                   'F'    [0.999003767967,1]
varDMinTauSignificance        varDMinTauSignificance        varDMinTauSignificance        varDMinTauSignificance                                          'F'    [-4.99987602234,177.313644409]
varKaonMinPT                  varKaonMinPT                  varKaonMinPT                  varKaonMinPT                                                    'F'    [100.069602966,12543.5996094]
varPionOneMinPT               varPionOneMinPT               varPionOneMinPT               varPionOneMinPT                                                 'F'    [100.037322998,6970.31054688]
varPionTwoMinPT               varPionTwoMinPT               varPionTwoMinPT               varPionTwoMinPT                                                 'F'    [108.954803467,15704.5585938]
varKaonMinVELOChi2ndof_log    varKaonMinVELOChi2ndof_log    varKaonMinVELOChi2ndof_log    varKaonMinVELOChi2ndof_log                                      'F'    [-6.67149019241,1.31319403648]
varKaonMinTChi2ndof_log       varKaonMinTChi2ndof_log       varKaonMinTChi2ndof_log       varKaonMinTChi2ndof_log                                         'F'    [-4.03133392334,1.11125946045]
varKaonMinMatchChi2_log       varKaonMinMatchChi2_log       varKaonMinMatchChi2_log       varKaonMinMatchChi2_log                                         'F'    [-3.14699935913,3.947234869]
varPionMinVELOChi2ndof_log    varPionMinVELOChi2ndof_log    varPionMinVELOChi2ndof_log    varPionMinVELOChi2ndof_log                                      'F'    [-7.79727935791,0.912339568138]
varPionMinTChi2ndof_log       varPionMinTChi2ndof_log       varPionMinTChi2ndof_log       varPionMinTChi2ndof_log                                         'F'    [-6.29380369186,0.710370540619]
varPionMinMatchChi2_log       varPionMinMatchChi2_log       varPionMinMatchChi2_log       varPionMinMatchChi2_log                                         'F'    [-3.62590193748,3.07249689102]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTG_MaxDepth2Node
   
#ifndef BDTG_MaxDepth2Node__def
#define BDTG_MaxDepth2Node__def
   
class BDTG_MaxDepth2Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTG_MaxDepth2Node ( BDTG_MaxDepth2Node* left,BDTG_MaxDepth2Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTG_MaxDepth2Node();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTG_MaxDepth2Node* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTG_MaxDepth2Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTG_MaxDepth2Node*   fLeft;     // pointer to the left daughter node
   BDTG_MaxDepth2Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTG_MaxDepth2Node::~BDTG_MaxDepth2Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTG_MaxDepth2Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTG_MaxDepth2Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG_MaxDepth2 : public IClassifierReader {

 public:

   // constructor
   ReadBDTG_MaxDepth2( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG_MaxDepth2" ),
        fNvars( 13 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "varDTFChi2ndof_log", "varIPChi2_log", "varBDIRAOwnPV", "varDMinTauSignificance", "varKaonMinPT", "varPionOneMinPT", "varPionTwoMinPT", "varKaonMinVELOChi2ndof_log", "varKaonMinTChi2ndof_log", "varKaonMinMatchChi2_log", "varPionMinVELOChi2ndof_log", "varPionMinTChi2ndof_log", "varPionMinMatchChi2_log" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG_MaxDepth2() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[13];
   double fVmax[13];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[13];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTG_MaxDepth2Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG_MaxDepth2::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTG_MaxDepth2Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTG_MaxDepth2Node*)current->GetRight();
         else current=(BDTG_MaxDepth2Node*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG_MaxDepth2::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337,-0.100384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0663493,-0.303524) , 
0, 0.583352, 1, 0, 0.161548,-0.338452) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41801,-0.0487412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.915581,0.203645) , 
2, 0.999976, 1, 0, 0.851451,0.351451) , 
3, 1.78984, 1, 0, 0.502779,0.00277917)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0620827,-0.239324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.294594,-0.0648796) , 
4, 748.931, 1, 0, 0.144837,-0.240815) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420456,-0.0712691) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.899425,0.164221) , 
4, 530.253, 1, 0, 0.818515,0.247116) , 
3, 1.3742, 1, 0, 0.50058,0.0168428)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0659366,-0.197031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329091,-0.0208306) , 
3, -0.103205, 1, 0, 0.16708,-0.155519) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.92438,0.148865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595696,-0.0113446) , 
0, 0.850469, 1, 0, 0.854845,0.211108) , 
3, 1.92324, 1, 0, 0.499085,0.0214629)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.114445,-0.157533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468922,0.0277063) , 
4, 748.775, 1, 0, 0.255202,-0.0866992) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555908,-0.00764279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.959742,0.145686) , 
2, 0.999976, 1, 0, 0.913767,0.213661) , 
3, 3.89842, 1, 0, 0.496924,0.0235464)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54631,0.0675629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.159262,-0.118093) , 
0, 0.400761, 1, 0, 0.277775,-0.0549254) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.966367,0.137864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711968,0.0287542) , 
0, 0.902084, 1, 0, 0.924219,0.175862) , 
3, 4.56124, 1, 0, 0.503796,0.0257664)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0802629,-0.171762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284585,-0.0250124) , 
4, 359.235, 1, 0, 0.153281,-0.103741) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261263,-0.103929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.765587,0.0998017) , 
2, 0.999976, 1, 0, 0.690931,0.092708) , 
4, 562.109, 1, 0, 0.500717,0.0232067)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2081,-0.0988001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.89058,0.080571) , 
3, 6.40348, 1, 0, 0.345888,-0.0575274) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0883573,-0.10073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.80521,0.116699) , 
3, -0.552857, 1, 0, 0.676381,0.109699) , 
10, -0.574669, 1, 0, 0.500827,0.0208703)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.213765,-0.0999812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.910657,0.0789424) , 
3, 8.68415, 1, 0, 0.315153,-0.0660926) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770121,0.107767) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281538,-0.0411074) , 
0, 0.880674, 1, 0, 0.635788,0.0797761) , 
7, -0.439542, 1, 0, 0.504168,0.0198975)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0740484,-0.183383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270149,-0.0366338) , 
5, 421.454, 1, 0, 0.146624,-0.105673) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.066157,-0.116837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.744362,0.073875) , 
3, -0.54889, 1, 0, 0.589375,0.0443369) , 
2, 0.999976, 1, 0, 0.502412,0.0148726)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653848,0.0547489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215333,-0.0806704) , 
0, 0.213999, 1, 0, 0.319996,-0.0313159) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487699,-0.0241575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.852495,0.109813) , 
5, 268.385, 1, 0, 0.766745,0.0814177) , 
4, 1010.67, 1, 0, 0.500239,0.0141669)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.256471,-0.0877565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.562701,0.0455571) , 
7, -0.0500447, 1, 0, 0.328386,-0.0422887) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115114,-0.0956756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.741002,0.0819471) , 
4, 316.409, 1, 0, 0.649254,0.0585158) , 
10, -0.669072, 1, 0, 0.501117,0.0119767)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726825,0.0731486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463345,-0.057384) , 
11, -0.108233, 1, 0, 0.683658,0.0490395) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.128939,-0.126386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364518,-0.00082661) , 
5, 435.307, 1, 0, 0.229651,-0.0458099) , 
0, 0.764302, 1, 0, 0.501459,0.0109751)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.268115,-0.0492835) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.92704,0.0762963) , 
3, 7.6614, 1, 0, 0.396959,-0.0197412) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.783368,0.101934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524513,-0.0102079) , 
8, 0.0799405, 1, 0, 0.732349,0.0699864) , 
10, -0.357212, 1, 0, 0.498254,0.00735855)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.208197,-0.0959289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564645,0.0175708) , 
10, -0.27469, 1, 0, 0.26501,-0.0513896) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.145006,-0.10742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655205,0.0576264) , 
2, 0.999952, 1, 0, 0.595142,0.0327292) , 
7, -0.63429, 1, 0, 0.497008,0.00772432)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.163553,-0.0391392) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0750644,-0.127604) , 
8, -0.268461, 1, 0, 0.102959,-0.0515294) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.032968,-0.155478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720205,0.0479309) , 
3, -1.53832, 1, 0, 0.636956,0.0265385) , 
4, 403.57, 1, 0, 0.500606,0.00660479)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382563,-0.0169395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.713559,0.0674781) , 
7, -0.357281, 1, 0, 0.56224,0.0230919) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381903,-0.0327181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207658,-0.124609) , 
8, -0.0680159, 1, 0, 0.301603,-0.0476389) , 
11, -0.143797, 1, 0, 0.501527,0.00661578)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.351612,-0.0524628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.671923,0.0455944) , 
10, -1.01311, 1, 0, 0.596855,0.0171994) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.179124,-0.0735532) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0701576,-0.185274) , 
0, 1.45581, 1, 0, 0.154382,-0.0515436) , 
0, 1.04819, 1, 0, 0.493527,0.00114628)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359743,-0.00496506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181473,-0.113831) , 
9, 1.77989, 1, 0, 0.319384,-0.0172012) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508153,-0.0350915) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.850983,0.0816958) , 
6, 887.435, 1, 0, 0.771472,0.0407721) , 
4, 1010.57, 1, 0, 0.502152,0.00623601)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316789,-0.048625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.622786,0.047493) , 
5, 263.776, 1, 0, 0.544636,0.0175453) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.344867,-0.0469322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2022,-0.136998) , 
8, 0.287281, 1, 0, 0.26453,-0.0568282) , 
8, 0.180556, 1, 0, 0.502652,0.00639792)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.220037,-0.0370637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.585043,0.0686532) , 
4, 1829.9, 1, 0, 0.252386,-0.0165321) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.953458,0.080256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.653021,-0.0197313) , 
0, 0.948358, 1, 0, 0.911077,0.034298) , 
3, 3.89381, 1, 0, 0.494309,0.00213675)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450036,0.000586107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.754353,0.0737868) , 
7, -0.194695, 1, 0, 0.578464,0.0211939) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.206536,-0.0690091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.901246,0.043871) , 
3, 6.1841, 1, 0, 0.358262,-0.0274452) , 
11, -0.254626, 1, 0, 0.497517,0.00331409)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611543,0.0434682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386237,-0.0726146) , 
12, 1.43788, 1, 0, 0.581629,0.018899) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.238244,-0.0780902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.705204,0.0222132) , 
4, 1155.45, 1, 0, 0.371767,-0.0263131) , 
8, -0.0761585, 1, 0, 0.498206,0.000926492)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.1062,-0.129009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183725,-0.034331) , 
6, 1286.18, 1, 0, 0.148516,-0.0418281) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397355,-0.0502614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.715714,0.0621019) , 
2, 0.999998, 1, 0, 0.587867,0.013686) , 
2, 0.999976, 1, 0, 0.500524,0.00264983)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29176,-0.044984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634671,0.0488892) , 
7, -0.889033, 1, 0, 0.574492,0.0215109) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.158674,-0.0670432) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.847575,0.0224574) , 
3, 2.90541, 1, 0, 0.408522,-0.0190899) , 
9, 1.30692, 1, 0, 0.497926,0.00278077)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67672,0.0212831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240216,-0.0455102) , 
0, 0.423953, 1, 0, 0.397421,-0.00882879) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.276592,-0.0196704) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.818825,0.0735114) , 
2, 0.999976, 1, 0, 0.741098,0.0350392) , 
10, -0.357651, 1, 0, 0.502008,0.0045209)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.179885,-0.0296882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.733246,0.0455298) , 
4, 562.22, 1, 0, 0.551629,0.0148795) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498859,-0.00229901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315478,-0.079617) , 
8, -0.217269, 1, 0, 0.391117,-0.0248913) , 
12, 1.14516, 1, 0, 0.501598,0.00248303)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0655531,-0.144441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145067,-0.044724) , 
2, 0.999882, 1, 0, 0.108677,-0.0393517) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.33661,-0.0407164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692177,0.0413557) , 
2, 0.999996, 1, 0, 0.555133,0.00747024) , 
2, 0.999951, 1, 0, 0.496966,0.00136998)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483133,0.0102969) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.287549,-0.0650974) , 
11, -0.302109, 1, 0, 0.397724,-0.0106332) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.763146,0.0505228) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244415,-0.0403109) , 
0, 1.13551, 1, 0, 0.6924,0.0230194) , 
7, -0.125563, 1, 0, 0.501436,0.00121083)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.250008,-0.00840843) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306136,-0.0955338) , 
6, 2769.99, 1, 0, 0.255288,-0.0113551) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.844605,0.000480762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.953829,0.0865695) , 
5, 420.018, 1, 0, 0.916579,0.0247696) , 
3, 3.89347, 1, 0, 0.500415,0.00203557)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0994937,-0.0541117) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343408,0.0329533) , 
3, 0.596348, 1, 0, 0.138316,-0.0152347) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.241414,-0.063532) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.871753,0.0416269) , 
4, 315.22, 1, 0, 0.821337,0.0169588) , 
3, 1.3742, 1, 0, 0.497994,0.00171841)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.148111,-0.0890649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381955,-0.0102713) , 
5, 267.654, 1, 0, 0.307835,-0.0159476) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.141215,-0.0649525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674412,0.0379002) , 
2, 0.999952, 1, 0, 0.614713,0.0146034) , 
10, -0.787098, 1, 0, 0.497377,0.00292213)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.118951,-0.0344896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701521,0.0391539) , 
4, 403.67, 1, 0, 0.56966,0.0143) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463224,-0.0147541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218198,-0.12959) , 
9, 1.91894, 1, 0, 0.428285,-0.0137956) , 
12, 0.900746, 1, 0, 0.503016,0.00105573)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.143061,-0.00780457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.841424,0.0623138) , 
3, 0.571827, 1, 0, 0.624462,0.0230707) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5456,0.0117433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330745,-0.0525401) , 
11, -0.314631, 1, 0, 0.446031,-0.00804779) , 
8, -0.367723, 1, 0, 0.496936,0.000830019)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.128352,-0.0410423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315166,0.0237989) , 
7, -0.00495712, 1, 0, 0.163841,-0.0119738) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.899434,0.0443222) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496899,-0.0405301) , 
0, 1.08963, 1, 0, 0.855221,0.0145235) , 
3, 1.92403, 1, 0, 0.499591,0.000893859)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35652,-0.0233499) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.7699,0.0565762) , 
4, 1788.51, 1, 0, 0.417689,-0.00529955) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.717583,0.0281502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.783652,0.0768565) , 
10, -0.129896, 1, 0, 0.757092,0.0274699) , 
10, -0.27469, 1, 0, 0.498711,0.0025231)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.83469,0.0809283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.834964,0.0416573) , 
6, 1633.04, 1, 0, 0.834823,0.0352933) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311839,-0.0389016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58592,0.0147615) , 
5, 435.173, 1, 0, 0.44865,-0.00492875) , 
0, -0.145486, 1, 0, 0.503968,0.000832917)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.293857,-0.0357461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626147,0.0274023) , 
7, -0.675416, 1, 0, 0.536969,0.00583852) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.312673,-0.0488309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.151153,-0.133199) , 
8, 0.377524, 1, 0, 0.261762,-0.0303807) , 
8, 0.186873, 1, 0, 0.49749,0.00064282)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27349,-0.0483582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567585,0.0180443) , 
10, -1.34379, 1, 0, 0.529306,0.0046346) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.265146,-0.018641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.160162,-0.143549) , 
11, 0.11037, 1, 0, 0.208005,-0.032956) , 
11, 0.0270365, 1, 0, 0.499907,0.001195)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561046,0.0241321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299061,-0.0685171) , 
12, 1.57471, 1, 0, 0.536994,0.00796787) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357769,-0.0329251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213416,-0.119647) , 
11, -0.469206, 1, 0, 0.263641,-0.0327762) , 
9, 1.96426, 1, 0, 0.504272,0.00309054)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506413,0.0210825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350239,-0.0313397) , 
11, -0.560148, 1, 0, 0.39373,-0.00709874) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522359,-0.0289732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.881416,0.059966) , 
6, 884.826, 1, 0, 0.799334,0.0168391) , 
4, 1397.51, 1, 0, 0.499107,-0.000879681)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.048746,-0.116083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0121133,-0.0909493) , 
0, 0.772242, 1, 0, 0.0234349,-0.021871) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664522,0.0240592) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211338,-0.0412217) , 
0, 1.11774, 1, 0, 0.594655,0.00803836) , 
3, -1.60502, 1, 0, 0.500345,0.00310024)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414944,-0.0073247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.597031,-0.0938052) , 
6, 3422.89, 1, 0, 0.425276,-0.00593616) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657932,0.0116932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.836161,0.0638808) , 
5, 429.121, 1, 0, 0.766356,0.0171867) , 
10, -0.249766, 1, 0, 0.501977,-0.000736338)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0681633,-0.130745) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.252468,-0.0492618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655992,0.0284556) , 
2, 0.999993, 1, 0, 0.524641,0.0029767) , 
2, 0.999854, 1, 0, 0.50287,0.000820685)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35024,-0.00502278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454214,-0.0775409) , 
6, 3154.03, 1, 0, 0.356598,-0.00526218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.892386,0.000970214) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.973908,0.0885241) , 
7, -0.494148, 1, 0, 0.954363,0.0171477) , 
3, 8.34014, 1, 0, 0.493273,-0.000138314)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0310446,-0.121495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.00526557,-0.13946) , 
0, 0.730245, 1, 0, 0.0127864,-0.0208642) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602535,0.0173482) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250483,-0.107419) , 
9, 2.20938, 1, 0, 0.585485,0.00625617) , 
3, -1.81284, 1, 0, 0.50013,0.00221412)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616753,0.0293261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329679,-0.0488594) , 
11, -0.0531818, 1, 0, 0.58084,0.00960108) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470416,0.01203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328572,-0.0484265) , 
9, 0.919489, 1, 0, 0.3717,-0.0108311) , 
8, -0.0642194, 1, 0, 0.498824,0.00158845)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352853,-0.0085657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229535,-0.0632011) , 
12, 0.730315, 1, 0, 0.277428,-0.0165722) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370296,-0.0266709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.665557,0.0220087) , 
5, 263.959, 1, 0, 0.596636,0.00474837) , 
10, -0.906071, 1, 0, 0.49803,-0.00183772)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0169328,-0.087738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231495,-0.0508957) , 
3, 1.26864, 1, 0, 0.0656513,-0.0167186) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59625,0.0186617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.717397,-0.0685914) , 
5, 1440.62, 1, 0, 0.602961,0.0066486) , 
4, 311.125, 1, 0, 0.501521,0.00223702)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.379857,-0.00232261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401531,-0.0667657) , 
6, 2478.6, 1, 0, 0.382786,-0.00520877) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494111,-0.0301279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.887606,0.0577826) , 
5, 264.752, 1, 0, 0.79704,0.0131308) , 
4, 1314.07, 1, 0, 0.50035,-4.07736e-06)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.734338,0.039561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.740013,-0.00409644) , 
6, 1647.89, 1, 0, 0.737055,0.00983283) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.175358,-0.0514033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443113,0.0158706) , 
5, 427.353, 1, 0, 0.298369,-0.00556733) , 
0, 0.52868, 1, 0, 0.499064,0.00147813)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0806095,-0.0464312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.648477,0.0207749) , 
4, 331.203, 1, 0, 0.538673,0.00556834) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.22611,-0.0671555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524984,0.000552361) , 
7, -0.290167, 1, 0, 0.353947,-0.0134499) , 
12, 1.27537, 1, 0, 0.49605,0.0011801)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.260317,-0.0868992) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210737,-0.0219019) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.748125,0.0181365) , 
4, 707.071, 1, 0, 0.509701,0.000954665) , 
6, 487.715, 1, 0, 0.496925,-0.000841871)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.286615,-0.0617815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440173,-0.00396042) , 
6, 718.083, 1, 0, 0.422072,-0.00455487) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.822168,0.0783723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656307,0.0193532) , 
8, -0.467053, 1, 0, 0.693332,0.013721) , 
7, -0.035389, 1, 0, 0.497474,0.000525283)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.790743,0.027023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379916,-0.0157458) , 
0, -0.0734224, 1, 0, 0.44446,-0.0032622) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.672426,0.0146374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.9458,0.0765926) , 
5, 428.512, 1, 0, 0.837633,0.0159878) , 
4, 1948.25, 1, 0, 0.495813,-0.000747948)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57154,0.0110809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.118107,-0.0831109) , 
0, 1.33481, 1, 0, 0.530504,0.00242968) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.153443,-0.0239495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.294271,-0.0777196) , 
5, 366.021, 1, 0, 0.227738,-0.019156) , 
8, 0.233256, 1, 0, 0.495871,-3.9524e-05)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593786,0.0171345) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40138,-0.0221165) , 
9, 1.52481, 1, 0, 0.530414,0.00215805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27428,-0.035028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.143855,-0.128513) , 
11, 0.102346, 1, 0, 0.215702,-0.0236384) , 
11, -0.0128741, 1, 0, 0.493484,-0.000869081)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.056871,-0.107385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.236668,-0.0432114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.647258,0.0227759) , 
2, 0.999991, 1, 0, 0.530761,0.0028547) , 
2, 0.999879, 1, 0, 0.503034,0.00116124)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.123121,-0.0248343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.797679,0.0168589) , 
3, 1.3742, 1, 0, 0.458522,-0.000988785) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582628,0.0599334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.973015,0.0585713) , 
3, 3.89381, 1, 0, 0.808377,0.0205446) , 
10, -0.0921772, 1, 0, 0.50199,0.00168665)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.205915,-0.0707136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511307,0.0105301) , 
5, 155.384, 1, 0, 0.486727,0.00208663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.693753,-0.058172) , 
5, 1233.25, 1, 0, 0.502707,1.63655e-05)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0997053,-0.101116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32718,-0.0170085) , 
10, -0.823145, 1, 0, 0.210889,-0.0175033) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648719,0.021948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457334,-0.014883) , 
11, -0.403357, 1, 0, 0.546044,0.00109754) , 
7, -1.02379, 1, 0, 0.498695,-0.00153031)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.105848,-0.0313969) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.769747,0.0181036) , 
3, 0.818257, 1, 0, 0.48466,0.000241383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641697,-0.0708) , 
6, 3517.79, 1, 0, 0.492764,-0.00133836)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536278,0.0104218) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14115,-0.058654) , 
0, 0.395834, 1, 0, 0.254852,-0.0100205) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682314,0.0502771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531255,0.00754098) , 
9, 0.293141, 1, 0, 0.546974,0.004808) , 
10, -1.26388, 1, 0, 0.500756,0.00246191)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.722572,0.0862996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537852,0.0145835) , 
8, -0.415229, 1, 0, 0.585341,0.0146999) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339524,-0.0128851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.955222,0.0531673) , 
3, 8.57955, 1, 0, 0.472281,-0.0015751) , 
12, 0.341435, 1, 0, 0.496956,0.00197681)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.259959,-0.0306882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60835,0.0052481) , 
10, -0.441843, 1, 0, 0.369891,-0.00704136) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652576,0.0339372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743861,-0.0146183) , 
6, 2391.24, 1, 0, 0.670992,0.0100515) , 
7, -0.244793, 1, 0, 0.504441,0.000596753)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.310739,-0.000725603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333047,-0.0426529) , 
6, 1995.45, 1, 0, 0.316738,-0.0048265) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611912,-0.00879829) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.871588,0.041655) , 
6, 1262.61, 1, 0, 0.768409,0.00744302) , 
4, 1010.57, 1, 0, 0.500456,0.000164165)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0274393,-0.0225876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.317191,-0.0390465) , 
3, 1.51043, 1, 0, 0.0930286,-0.00782958) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.124322,-0.059432) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.680229,0.0159939) , 
2, 0.999903, 1, 0, 0.647413,0.00522242) , 
4, 403.57, 1, 0, 0.507286,0.00192339)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501357,0.00416852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.681679,-0.0484199) , 
5, 1440.58, 1, 0, 0.509967,0.000455324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206509,-0.0856209) , 
12, 1.76549, 1, 0, 0.497735,-0.000651214)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.235368,-0.0131183) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.851236,0.0140285) , 
3, 3.27908, 1, 0, 0.41053,-0.0024992) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.992201,0.0823646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.928436,0.0545912) , 
0, 0.506547, 1, 0, 0.968579,0.0133038) , 
3, 11.9744, 1, 0, 0.499342,1.58099e-05)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378885,-0.00645461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.700713,0.0345589) , 
10, -0.843778, 1, 0, 0.594241,0.00776568) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.30286,-0.0207865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.74601,0.0198797) , 
4, 1486.34, 1, 0, 0.390913,-0.00428963) , 
8, -0.143032, 1, 0, 0.497484,0.00202898)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36775,-0.03503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538361,0.0131163) , 
6, 706.056, 1, 0, 0.52158,0.00320128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.153075,-0.0693883) , 
11, 0.0922393, 1, 0, 0.500732,0.00199992)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547741,0.0111423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198588,-0.0712708) , 
9, 2.21693, 1, 0, 0.531029,0.00301293) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.226036,-0.0280385) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154966,-0.0994396) , 
8, 0.38147, 1, 0, 0.190336,-0.0169299) , 
8, 0.280067, 1, 0, 0.502486,0.00134213)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0623652,-0.123877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.119602,-0.0128855) , 
6, 1204.07, 1, 0, 0.0939315,-0.0157118) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.372019,-0.0218653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.728217,0.0241086) , 
2, 0.999998, 1, 0, 0.544522,0.000753755) , 
2, 0.999927, 1, 0, 0.50192,-0.00080304)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640111,0.0362713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513336,0.00467266) , 
11, -0.74286, 1, 0, 0.533085,0.00374282) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.202543,-0.0569722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531709,-0.00232737) , 
10, -0.444612, 1, 0, 0.302906,-0.0119713) , 
12, 1.4526, 1, 0, 0.50122,0.00156746)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.24411,-0.00728872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372352,-0.0641095) , 
5, 1071.31, 1, 0, 0.254691,-0.00598379) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.971821,0.0572146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.734756,-0.0355773) , 
0, 0.745048, 1, 0, 0.913634,0.00410616) , 
3, 3.89381, 1, 0, 0.500469,-0.00222035)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428838,-0.00264748) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.829481,0.0242842) , 
4, 1314.07, 1, 0, 0.54547,0.00153322) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00855676,-0.0487152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.22445,-0.0648764) , 
3, -0.400645, 1, 0, 0.106831,-0.0132093) , 
0, 1.31576, 1, 0, 0.500586,2.46809e-05)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0771449,-0.0694963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408004,-0.0114113) , 
2, 0.999976, 1, 0, 0.327921,-0.00703535) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0319268,-0.0927494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.730751,0.0187344) , 
3, -1.53558, 1, 0, 0.641691,0.00418297) , 
7, -0.362705, 1, 0, 0.495923,-0.00102871)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0634107,-0.0756719) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.247298,-0.0186026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.645798,0.0189494) , 
2, 0.999991, 1, 0, 0.530784,0.00351447) , 
2, 0.999879, 1, 0, 0.503769,0.00238578)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52897,0.00673614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.853539,0.0770718) , 
10, 0.0445974, 1, 0, 0.548989,0.00383262) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36955,-0.0372983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0768187,0.0079518) , 
0, 0.920207, 1, 0, 0.251555,-0.00831064) , 
11, -0.0636708, 1, 0, 0.502903,0.00195106)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631204,0.0489824) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611712,-0.0227806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448962,0.00457759) , 
1, -1.31094, 1, 0, 0.490564,-0.00122249) , 
9, 0.0816478, 1, 0, 0.50057,0.000216617)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305226,-0.0507893) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626922,-0.00419367) , 
5, 211.503, 1, 0, 0.574327,-0.00426627) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647474,0.0471905) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181421,-0.00612832) , 
0, 0.790805, 1, 0, 0.351249,0.0062922) , 
1, 0.271793, 1, 0, 0.497551,-0.00063239)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534232,-0.018876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325582,0.0037991) , 
1, -0.0253329, 1, 0, 0.443955,-0.00379341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.978797,0.072912) , 
3, 17.2338, 1, 0, 0.496569,-0.00232889)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0691897,-0.00166095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.653125,-0.0215488) , 
3, 1.69387, 1, 0, 0.26666,-0.0040408) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618969,0.0250883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416199,-0.00805688) , 
9, 1.66033, 1, 0, 0.569847,0.00641402) , 
10, -1.06604, 1, 0, 0.499261,0.00398)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.00717223,-0.0548185) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0305598,-0.0989739) , 
4, 748.746, 1, 0, 0.0146433,-0.00868579) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.283544,-0.0289997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.63367,0.0101651) , 
7, -0.985751, 1, 0, 0.584617,0.00198805) , 
3, -1.81203, 1, 0, 0.501161,0.000425172)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406986,-0.0141072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.533468,-0.0617102) , 
6, 3408.71, 1, 0, 0.413095,-0.00650987) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978305,0.0256526) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.965234,0.0656398) , 
8, -0.240798, 1, 0, 0.971682,0.00855995) , 
3, 12.3079, 1, 0, 0.50109,-0.0041359)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.169804,0.0312529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.122139,-0.0398022) , 
6, 1287.02, 1, 0, 0.136761,-0.00417159) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703575,0.0186661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470585,-0.0309228) , 
9, 1.96963, 1, 0, 0.682395,0.00544801) , 
4, 530.171, 1, 0, 0.501616,0.00226085)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.825117,0.0403064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363398,-0.0300193) , 
0, 0.0187623, 1, 0, 0.453372,-0.00522246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385831,0.000694807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.71815,0.0417607) , 
10, -0.476048, 1, 0, 0.523397,0.00577748) , 
6, 1250.1, 1, 0, 0.499376,0.00200411)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509345,0.00372382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.716972,-0.0383401) , 
5, 1247.49, 1, 0, 0.525239,0.000126543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0760928,-0.109648) , 
0, 1.47117, 1, 0, 0.503585,-0.00081825)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615271,0.0210703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459919,-0.00457037) , 
11, -0.656298, 1, 0, 0.493099,0.000533541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.647891,-0.0624298) , 
6, 3541.96, 1, 0, 0.500944,-0.000724403)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425882,0.0272047) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.95581,-0.00757669) , 
3, 5.38922, 1, 0, 0.626896,0.00777515) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429584,0.00095036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565634,-0.0346744) , 
6, 2438.89, 1, 0, 0.452889,-0.00189696) , 
8, -0.39389, 1, 0, 0.499243,0.00067961)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.23021,-0.0217119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.573222,0.00612109) , 
7, -0.933582, 1, 0, 0.516244,0.000782261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178661,-0.0713185) , 
8, 0.336284, 1, 0, 0.495804,-0.000347268)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503879,0.0437003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5779,0.00869783) , 
6, 869.716, 1, 0, 0.56675,0.00512236) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516495,-0.00327625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341635,-0.0304706) , 
9, 1.22873, 1, 0, 0.4281,-0.00541272) , 
12, 0.866379, 1, 0, 0.497586,-0.000132916)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0304849,0.00799837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.105813,-0.0699121) , 
4, 964.972, 1, 0, 0.0471691,-0.00515567) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566391,0.00194149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.901466,0.0409714) , 
4, 1390.31, 1, 0, 0.670235,0.00437281) , 
3, -0.550468, 1, 0, 0.504564,0.00183921)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600908,-0.0348214) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668051,0.0571113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485017,0.000977254) , 
11, -0.790663, 1, 0, 0.495923,0.00156114) , 
11, -0.935827, 1, 0, 0.503684,0.000465145)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476243,-0.0107604) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.715122,0.0313799) , 
7, 0.125073, 1, 0, 0.515337,-0.00137943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.171427,-0.100587) , 
9, 2.24126, 1, 0, 0.498816,-0.00251419)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.665202,-0.0124907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.562799,0.0255179) , 
12, 0.665719, 1, 0, 0.604636,0.00383354) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.213174,-0.0415248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514804,-0.00617282) , 
5, 263.959, 1, 0, 0.432879,-0.00464215) , 
11, -0.485464, 1, 0, 0.495282,-0.00156277)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5745,-0.0465748) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634583,0.0241432) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457546,-0.00357777) , 
8, -0.39516, 1, 0, 0.498147,0.00113911) , 
8, -0.881534, 1, 0, 0.501489,0.000425426)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309314,0.0722846) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.786591,0.00728264) , 
4, 707.168, 1, 0, 0.596049,0.0124573) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540454,-0.0106084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304087,0.0239325) , 
1, 0.60867, 1, 0, 0.480845,-0.000918632) , 
12, 0.131098, 1, 0, 0.49807,0.00108131)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364283,-0.0237666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72168,0.0374939) , 
10, -0.308055, 1, 0, 0.45359,-0.0031176) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.12682,-0.019314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.752469,0.0237586) , 
4, 518.501, 1, 0, 0.525513,0.00382013) , 
6, 1261.48, 1, 0, 0.500353,0.00139318)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.837111,0.0404905) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514394,-0.00707989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295543,0.0230542) , 
9, 1.79901, 1, 0, 0.473682,-0.000751462) , 
0, -0.383815, 1, 0, 0.50077,0.000443399)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616233,-0.0186886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.603609,0.0276866) , 
9, 0.0277407, 1, 0, 0.606294,0.00662561) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.834701,0.0326759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426042,-0.0163477) , 
0, -0.315537, 1, 0, 0.461585,-0.00375218) , 
9, 0.848084, 1, 0, 0.502807,-0.000795911)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0474702,-0.0641513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.114653,0.0372479) , 
4, 253.11, 1, 0, 0.0654301,-0.00528307) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682254,-0.0327101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5871,0.011335) , 
12, -0.0322494, 1, 0, 0.597408,0.0025134) , 
4, 309.285, 1, 0, 0.49932,0.00107586)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443329,0.0255735) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.761657,0.00802716) , 
10, -0.668408, 1, 0, 0.624629,0.00619547) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.233624,-0.0416099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.143277,0.00495929) , 
8, -0.269125, 1, 0, 0.172975,-0.00318102) , 
0, 0.983017, 1, 0, 0.50367,0.00368432)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555576,-0.0306305) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.172136,0.00179925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.855561,0.0231272) , 
3, 1.92324, 1, 0, 0.501548,0.00387185) , 
11, -1.02208, 1, 0, 0.504367,0.00307987)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644132,-0.0360351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489796,0.00908443) , 
12, 1.2587, 1, 0, 0.610003,-0.0097144) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0764723,-0.025761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.723522,0.0128832) , 
3, 0.567626, 1, 0, 0.457357,0.000464377) , 
1, -1.15406, 1, 0, 0.502595,-0.00255217)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.113473,-0.0524354) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0740309,0.000293632) , 
9, 1.33543, 1, 0, 0.0922634,-0.00633447) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843764,-0.0143505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500192,0.0166174) , 
0, 0.324659, 1, 0, 0.640659,0.00182114) , 
4, 403.67, 1, 0, 0.500805,-0.000258733)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.191955,-0.0157756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.865004,0.00950776) , 
3, 2.9006, 1, 0, 0.454087,-0.00242007) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.784473,0.0593732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.820975,0.0139715) , 
6, 1688.89, 1, 0, 0.801833,0.0110361) , 
10, -0.113746, 1, 0, 0.501827,-0.000572757)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632323,-0.0571479) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58621,0.030921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472935,0.00129445) , 
12, 0.181489, 1, 0, 0.491091,0.00220157) , 
1, -3.03067, 1, 0, 0.500059,0.000739402)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603441,0.00976815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377341,-0.0126969) , 
8, -0.0719269, 1, 0, 0.515673,0.000555247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238047,-0.0573372) , 
12, 1.69866, 1, 0, 0.500124,-0.000356769)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595875,0.0161942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.760344,-0.0213833) , 
5, 1083.57, 1, 0, 0.616172,0.00444448) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0353185,-0.00548409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513594,-0.0424992) , 
3, 1.79251, 1, 0, 0.169642,-0.00664154) , 
0, 1.00277, 1, 0, 0.503434,0.00164554)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0491458,-0.117573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208756,0.0265415) , 
5, 421.454, 1, 0, 0.108055,-0.00942046) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411298,-0.0168505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.742245,0.0316046) , 
2, 0.999999, 1, 0, 0.554414,0.00182481) , 
2, 0.999951, 1, 0, 0.497432,0.000389247)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297711,-0.0431255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930306,0.0246782) , 
3, 3.39016, 1, 0, 0.584878,-0.00758735) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.088836,-0.0404251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513103,0.0098372) , 
2, 0.999952, 1, 0, 0.453327,0.0016746) , 
9, 0.906612, 1, 0, 0.494741,-0.00124117)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.272436,-0.0252501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569708,0.00446761) , 
10, -1.26388, 1, 0, 0.524208,5.05585e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0530054,-0.00648602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470873,0.0536803) , 
4, 560.968, 1, 0, 0.255191,0.0102733) , 
9, 2.08455, 1, 0, 0.501283,0.000921688)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644308,0.029155) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.247207,0.0235808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.520887,-0.0113101) , 
10, -1.40912, 1, 0, 0.488552,-0.00238532) , 
9, 0.0816478, 1, 0, 0.498962,-0.00157898)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.672564,0.0429567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52008,-0.0096045) , 
12, 1.07386, 1, 0, 0.621153,0.00923231) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295648,-0.014772) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.753241,0.0112367) , 
4, 1010.68, 1, 0, 0.47501,-0.00154309) , 
9, 0.652558, 1, 0, 0.50543,0.000699808)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415289,0.0385648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.94462,-0.043886) , 
3, 4.65938, 1, 0, 0.629624,0.00807016) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460862,-0.0040691) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.623485,-0.0522736) , 
6, 3468.15, 1, 0, 0.469755,-0.00223834) , 
8, -0.519319, 1, 0, 0.497658,-0.000439114)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660939,0.00446558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473057,0.03514) , 
8, 0.0162585, 1, 0, 0.612276,0.00429279) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267379,0.00939545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546261,-0.018837) , 
7, -0.399339, 1, 0, 0.416527,-0.00205086) , 
11, -0.407148, 1, 0, 0.506183,0.000854597)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58165,-0.0485218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608238,-0.0118706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463488,0.0111792) , 
1, -1.32834, 1, 0, 0.500534,0.00148403) , 
8, -0.881534, 1, 0, 0.504222,0.000650892)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638955,0.0257068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508012,-8.43743e-05) , 
1, -2.29845, 1, 0, 0.524262,0.00123178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0753245,-0.0939885) , 
0, 1.45208, 1, 0, 0.499036,0.000374346)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574604,-0.0198691) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418657,0.0017686) , 
11, -0.538861, 1, 0, 0.465394,-0.00170386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.853228,0.0486954) , 
4, 2262.4, 1, 0, 0.499523,-0.000537689)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.310457,0.0278913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292193,-0.0361596) , 
6, 2465.59, 1, 0, 0.30815,0.00651374) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661886,-0.0215388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.874179,0.0215008) , 
6, 1641.56, 1, 0, 0.760142,-0.000740124) , 
4, 964.999, 1, 0, 0.498249,0.0034629)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.681309,-0.0034204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499057,0.0292327) , 
1, 0.290447, 1, 0, 0.62274,0.00245362) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.200282,-0.0326296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.68486,-0.00216938) , 
4, 793.129, 1, 0, 0.435589,-0.00504926) , 
8, -0.309386, 1, 0, 0.49912,-0.00250229)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534318,0.0453073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.898649,0.00534857) , 
4, 620.352, 1, 0, 0.809148,0.00756405) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.189269,0.00272019) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.868728,-0.0298939) , 
3, 3.89426, 1, 0, 0.406358,-0.00198872) , 
0, 0.0929877, 1, 0, 0.499752,0.000226258)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606604,0.022526) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488104,-0.00299456) , 
12, 0.353455, 1, 0, 0.51473,0.00101581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.230076,0.06728) , 
1, 1.79334, 1, 0, 0.50259,0.00174222)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.238899,-0.0287799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660904,0.0237499) , 
4, 1696.28, 1, 0, 0.299965,-0.00622069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594555,0.00745777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.764491,-0.0258304) , 
7, 0.189019, 1, 0, 0.618105,0.00114347) , 
10, -0.792597, 1, 0, 0.496976,-0.00166036)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317655,-0.0404064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0740012,0.00579192) , 
0, 0.18416, 1, 0, 0.110148,-0.00311628) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.848422,-0.0306089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.765953,0.0198848) , 
8, -0.58487, 1, 0, 0.778916,0.00442958) , 
3, 0.818257, 1, 0, 0.499516,0.00127705)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67861,-0.00220927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.54973,0.056032) , 
12, 0.967107, 1, 0, 0.625007,0.00838921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390241,-0.0107883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.970367,0.0585121) , 
3, 11.9744, 1, 0, 0.477377,-0.00189983) , 
8, -0.519319, 1, 0, 0.502839,-0.000125256)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601757,0.0289272) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534017,-0.0155381) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323834,0.00785398) , 
9, 1.80737, 1, 0, 0.49534,-0.00376557) , 
8, -0.788609, 1, 0, 0.502231,-0.00284792)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.097065,-0.0663051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572402,-6.80654e-05) , 
2, 0.999976, 1, 0, 0.450004,-0.00400659) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417061,0.0211403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.659049,-0.00886006) , 
5, 591.897, 1, 0, 0.521298,0.00231276) , 
6, 1261.48, 1, 0, 0.496109,8.00283e-05)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699117,0.0331417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535216,-0.0011296) , 
1, -1.11722, 1, 0, 0.586823,0.00361029) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57055,-0.0225813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398282,0.00225855) , 
8, -0.275173, 1, 0, 0.460571,-0.00218144) , 
9, 0.848084, 1, 0, 0.49662,-0.00052771)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.118244,-0.0297977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572667,0.0239116) , 
2, 0.999976, 1, 0, 0.464085,0.00500927) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288183,-0.0149889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.954105,0.0386462) , 
3, 4.56682, 1, 0, 0.545775,-0.00097638) , 
6, 1630.48, 1, 0, 0.5011,0.00229705)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573801,-0.0525425) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570346,0.0129263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394498,-0.0141634) , 
9, 1.35178, 1, 0, 0.493478,0.000516905) , 
12, -0.268036, 1, 0, 0.498597,-0.000670949)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614045,0.0304082) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496816,-0.0024841) , 
12, 0.121367, 1, 0, 0.513782,0.000820099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207691,0.0809705) , 
1, 1.81719, 1, 0, 0.501397,0.00166476)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.230165,0.0398255) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511585,-0.00194083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.699613,-0.0493279) , 
5, 1440.58, 1, 0, 0.521108,-0.0014874) , 
7, -1.41072, 1, 0, 0.501597,-0.000650557)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544978,-0.020346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401688,0.0109589) , 
9, 1.30692, 1, 0, 0.477926,-0.00203642) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677984,-0.00848215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.63073,0.0570405) , 
12, 0.647746, 1, 0, 0.647797,0.0124346) , 
6, 2770.46, 1, 0, 0.498349,-0.000296579)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.185011,-0.0548944) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590331,-0.0429074) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516892,0.00679348) , 
11, -0.997965, 1, 0, 0.521016,0.00122982) , 
7, -1.41328, 1, 0, 0.499189,0.000276178)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402407,-0.00451635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.664574,0.0144427) , 
5, 427.881, 1, 0, 0.539203,0.00195846) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0589554,-0.00307066) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628866,-0.0657227) , 
3, 1.38231, 1, 0, 0.270709,-0.00967882) , 
9, 1.89657, 1, 0, 0.499962,0.000257621)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.250637,-0.0826227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497009,0.00235007) , 
5, 195.743, 1, 0, 0.457707,-0.00335306) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639298,0.024897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478173,-0.00103451) , 
1, -0.792654, 1, 0, 0.535684,0.00280575) , 
6, 1451.34, 1, 0, 0.501038,6.9396e-05)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.242354,-0.0451903) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76991,-0.0138207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3539,0.00647958) , 
0, 0.394753, 1, 0, 0.518076,-0.000707992) , 
10, -1.65956, 1, 0, 0.498838,-0.00159808)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.236982,-0.0525449) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410822,0.0110235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.723708,-0.00763884) , 
10, -0.380095, 1, 0, 0.513862,0.00172001) , 
10, -1.88747, 1, 0, 0.50133,0.000947207)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266137,-0.0593296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.55025,-0.00219348) , 
6, 501.316, 1, 0, 0.535635,-0.00162377) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.253061,0.0228667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472794,0.0653329) , 
5, 574.955, 1, 0, 0.328996,0.0108972) , 
9, 1.82083, 1, 0, 0.498874,0.000603702)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633305,0.0134426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462935,-0.0128833) , 
11, -0.438794, 1, 0, 0.533217,-0.000551815) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.222512,-0.00762906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52519,-0.0553217) , 
10, -0.542389, 1, 0, 0.343164,-0.0083362) , 
12, 1.35448, 1, 0, 0.49711,-0.00203075)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.34906,0.0298809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.651318,-0.0359968) , 
7, -0.705198, 1, 0, 0.578377,-0.00633452) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515429,0.0149256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229768,-0.0296329) , 
1, 1.204, 1, 0, 0.481285,0.00347744) , 
12, 0.294446, 1, 0, 0.500832,0.00150208)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.748553,0.035948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.821524,-0.00373457) , 
5, 427.96, 1, 0, 0.791774,0.00542803) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219823,-0.0393558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509001,0.00474367) , 
5, 322.969, 1, 0, 0.396828,-0.00290077) , 
0, 0.158107, 1, 0, 0.500283,-0.000719067)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582508,-0.0408792) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640537,-0.0352853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479935,0.00260108) , 
1, -2.86217, 1, 0, 0.491858,-0.000300889) , 
12, -0.185684, 1, 0, 0.498591,-0.00131126)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.190886,0.0273665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223872,-0.0503897) , 
6, 1029.31, 1, 0, 0.215643,-0.00815506) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541555,0.0142684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720234,-0.0433244) , 
5, 1273.08, 1, 0, 0.554795,0.0033364) , 
7, -0.970183, 1, 0, 0.500305,0.00149014)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.260585,0.0637688) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219743,-0.0127678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.734956,0.00975134) , 
4, 707.071, 1, 0, 0.511435,0.000190158) , 
10, -1.84925, 1, 0, 0.49869,0.00117119)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662901,0.0357766) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552935,0.0110105) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381895,-0.0171749) , 
9, 1.47822, 1, 0, 0.492793,0.000549123) , 
1, -2.875, 1, 0, 0.50511,0.0015841)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.188961,-0.0807844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460102,-0.00600801) , 
5, 147.4, 1, 0, 0.437374,-0.00344328) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.760947,-0.00527819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609973,0.0399151) , 
1, -0.252774, 1, 0, 0.682745,0.00594427) , 
5, 747.55, 1, 0, 0.500338,-0.00103436)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.252094,-0.0118205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.732105,0.0127212) , 
4, 793.157, 1, 0, 0.489412,0.000231226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660904,-0.0496627) , 
6, 3532.38, 1, 0, 0.498074,-0.000692735)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648927,-0.0306685) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0951741,-0.0145112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.750577,0.00629077) , 
3, 0.595635, 1, 0, 0.487987,-0.000203921) , 
1, -2.82279, 1, 0, 0.499981,-0.000986145)    );
  // itree = 150
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675243,-0.0231692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575022,0.0157943) , 
9, 0.486633, 1, 0, 0.590893,0.00337696) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.149947,0.00176776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479987,-0.0274359) , 
2, 0.999976, 1, 0, 0.362108,-0.00530933) , 
1, 0.0308433, 1, 0, 0.496711,-0.000198834)    );
  // itree = 151
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650259,0.024477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.433735,0.00370772) , 
8, -0.129478, 1, 0, 0.55228,0.00493417) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.334116,-0.0194341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62069,0.0405893) , 
7, 0.0484111, 1, 0, 0.389717,-0.00224629) , 
12, 1.11199, 1, 0, 0.497261,0.00250393)    );
  // itree = 152
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.093456,-0.0292709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526738,0.0181689) , 
2, 0.999976, 1, 0, 0.421588,0.00348008) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708156,0.00197255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421802,-0.0491796) , 
8, 0.0950759, 1, 0, 0.649781,-0.00261395) , 
5, 591.934, 1, 0, 0.505686,0.00123418)    );
  // itree = 153
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415783,-0.00478429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.762444,0.0217144) , 
10, -0.249766, 1, 0, 0.49289,0.000124421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.695092,0.0419315) , 
7, 0.339452, 1, 0, 0.505528,0.000990666)    );
  // itree = 154
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724898,0.0459951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569039,0.00202751) , 
1, -2.26529, 1, 0, 0.589251,0.00270161) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407274,-0.00754698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600824,-0.0485946) , 
7, 0.195928, 1, 0, 0.428505,-0.00366264) , 
9, 1.17875, 1, 0, 0.502494,-0.000733271)    );
  // itree = 155
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39071,0.0435341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.719833,-0.00016302) , 
2, 0.999976, 1, 0, 0.686962,0.00192658) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347253,0.0248509) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208085,-0.0351011) , 
11, -0.715257, 1, 0, 0.22965,-0.00562322) , 
0, 0.736932, 1, 0, 0.497859,-0.00119534)    );
  // itree = 156
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.22443,-0.0485894) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.798252,-0.0172583) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421544,0.0080769) , 
0, 0.128801, 1, 0, 0.514981,0.00039739) , 
10, -1.71734, 1, 0, 0.49668,-0.000513389)    );
  // itree = 157
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70438,0.0293713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.612029,0.0607137) , 
12, 0.859997, 1, 0, 0.65895,0.0167245) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473802,0.00061923) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692115,0.0467206) , 
5, 1411.48, 1, 0, 0.485303,0.00111723) , 
1, -2.64798, 1, 0, 0.50024,0.00245973)    );
  // itree = 158
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472949,0.00081529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.679856,-0.0306027) , 
5, 1105.44, 1, 0, 0.493721,-0.000818882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669286,-0.0607183) , 
7, 0.361787, 1, 0, 0.502812,-0.00169783)    );
  // itree = 159
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627973,-0.0460391) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550846,0.0103549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301269,-0.0180684) , 
8, 0.0628085, 1, 0, 0.487573,0.00122351) , 
1, -2.99406, 1, 0, 0.496566,4.36346e-05)    );
  // itree = 160
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376629,0.0178003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.673909,-0.0214433) , 
10, -1.04829, 1, 0, 0.60619,-0.0038249) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0738779,-0.0111294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.702758,0.0253888) , 
3, 0.592075, 1, 0, 0.420947,0.00421139) , 
8, -0.235826, 1, 0, 0.497965,0.000870156)    );
  // itree = 161
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.646108,0.00415683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222561,-0.027841) , 
0, 0.511944, 1, 0, 0.394219,-0.00327857) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.128398,-0.0431027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.759833,0.0211619) , 
4, 309.285, 1, 0, 0.686668,0.00448963) , 
7, -0.141715, 1, 0, 0.500194,-0.000463598)    );
  // itree = 162
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.258744,0.0619375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58678,-0.00218557) , 
7, -1.35549, 1, 0, 0.563976,0.00058395) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471885,0.0536001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0940591,-0.00672053) , 
0, 1.17854, 1, 0, 0.33154,0.0110521) , 
1, 0.582521, 1, 0, 0.503611,0.00330257)    );
  // itree = 163
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673141,-0.0791901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.568809,-0.00666096) , 
1, -2.86024, 1, 0, 0.576531,-0.00411035) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462765,0.0457953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.296876,0.00193555) , 
8, 0.0925363, 1, 0, 0.353184,0.00533322) , 
8, -0.0176025, 1, 0, 0.502482,-0.000979387)    );
  // itree = 164
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671065,0.00735786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453701,0.0564052) , 
1, 0.848951, 1, 0, 0.631479,0.00542382) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234085,0.0167248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522402,-0.0131247) , 
10, -1.06604, 1, 0, 0.453535,-0.00199294) , 
8, -0.373749, 1, 0, 0.502813,6.0992e-05)    );
  // itree = 165
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.672346,-0.0129974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565118,0.021684) , 
11, -0.547517, 1, 0, 0.600372,0.00334235) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644316,-0.0263491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227196,0.00738333) , 
0, 0.541605, 1, 0, 0.405874,-0.00310327) , 
8, -0.185321, 1, 0, 0.497736,-5.90035e-05)    );
  // itree = 166
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465666,-0.0471413) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.814396,-0.00507827) , 
10, -0.548059, 1, 0, 0.633062,-0.00939775) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623878,0.0409866) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46761,-0.00140754) , 
8, -0.457053, 1, 0, 0.476024,0.000338664) , 
8, -0.527828, 1, 0, 0.502101,-0.0012781)    );
  // itree = 167
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686397,0.0297768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.593529,0.0194865) , 
12, 0.829778, 1, 0, 0.640001,0.0100363) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503366,-0.0111218) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270806,0.0371222) , 
12, 1.60649, 1, 0, 0.483898,-0.00236999) , 
1, -2.64798, 1, 0, 0.497739,-0.00126999)    );
  // itree = 168
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0422816,-0.00848019) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394368,-0.0560236) , 
4, 578.196, 1, 0, 0.207887,-0.0113317) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638082,0.0346593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523951,-0.00534329) , 
12, -0.340781, 1, 0, 0.530419,-0.000899075) , 
7, -1.21854, 1, 0, 0.500139,-0.00187851)    );
  // itree = 169
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.321465,-0.0385081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188951,0.0108107) , 
11, -0.28728, 1, 0, 0.263594,-0.00583576) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566109,0.00888951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674128,-0.0239228) , 
6, 2381.51, 1, 0, 0.586995,0.00089623) , 
7, -0.675416, 1, 0, 0.4979,-0.000958393)    );
  // itree = 170
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399709,0.0451547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.856954,-0.00703132) , 
4, 562.283, 1, 0, 0.753383,0.00352366) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0797693,0.0174838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.706134,-0.033971) , 
3, 1.78984, 1, 0, 0.314926,-0.00270272) , 
0, 0.450737, 1, 0, 0.497833,-0.00010532)    );
  // itree = 171
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658294,0.0264488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492901,-0.00319946) , 
11, -0.539782, 1, 0, 0.544679,0.00209786) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.130586,0.0144979) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393871,-0.0600002) , 
2, 0.999976, 1, 0, 0.278902,-0.00824071) , 
1, 0.913094, 1, 0, 0.497159,0.000249363)    );
  // itree = 172
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572725,0.0501309) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609711,0.027307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.481844,-0.00402026) , 
12, -0.0255775, 1, 0, 0.495619,-6.39043e-05) , 
11, -1.041, 1, 0, 0.499351,0.000804106)    );
  // itree = 173
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.215307,-0.037991) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.892662,0.00683506) , 
3, 2.01876, 1, 0, 0.58137,-0.00634919) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604298,-0.0169319) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450964,0.0110515) , 
1, -1.86722, 1, 0, 0.477075,0.00168153) , 
12, 0.32961, 1, 0, 0.49968,-5.9048e-05)    );
  // itree = 174
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0142334,-0.0630219) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.616634,0.012682) , 
3, -1.81284, 1, 0, 0.534131,0.00316407) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.214797,0.00933143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485631,-0.0481769) , 
10, -0.599505, 1, 0, 0.333835,-0.00558083) , 
12, 1.34715, 1, 0, 0.496205,0.00150824)    );
  // itree = 175
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0806797,-0.10068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0929539,-0.0050231) , 
1, 0.683163, 1, 0, 0.0876099,-0.00923104) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.276588,-0.0220446) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.650169,0.0197786) , 
2, 0.999993, 1, 0, 0.537006,0.00281208) , 
2, 0.999927, 1, 0, 0.493469,0.00164538)    );
  // itree = 176
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421618,0.0524927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3154,0.0135061) , 
12, 0.185889, 1, 0, 0.331083,0.00636639) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582321,-0.0209679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.712489,0.013323) , 
7, 0.0201071, 1, 0, 0.636157,-0.00225714) , 
7, -0.411096, 1, 0, 0.503224,0.00150047)    );
  // itree = 177
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486782,-0.0300994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.81217,0.0230043) , 
10, -0.306236, 1, 0, 0.582749,-0.00535206) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.176944,0.0618618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487145,0.00500026) , 
7, -1.35075, 1, 0, 0.463221,0.0025703) , 
12, 0.595263, 1, 0, 0.503578,-0.000104632)    );
  // itree = 178
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535055,-0.0257979) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384712,0.0036098) , 
11, -0.575219, 1, 0, 0.425246,-0.00159142) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.789043,0.0452541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.582356,-0.0220537) , 
11, -0.316307, 1, 0, 0.70457,0.00540358) , 
7, -0.0187761, 1, 0, 0.499312,0.000263377)    );
  // itree = 179
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.120029,0.0179486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604266,-0.00765743) , 
4, 532.618, 1, 0, 0.4239,-0.000285332) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.936199,0.0364416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619347,-0.0312611) , 
0, -0.0324418, 1, 0, 0.687921,-0.00591016) , 
7, -0.035389, 1, 0, 0.497543,-0.00185426)    );
  // itree = 180
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309177,-0.00535447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.637927,0.0173747) , 
10, -0.868205, 1, 0, 0.531617,0.00327119) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0477608,0.0252981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506508,-0.0588002) , 
3, 0.74545, 1, 0, 0.244245,-0.008559) , 
9, 2.00572, 1, 0, 0.501342,0.00202488)    );
  // itree = 181
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.282085,0.0427079) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605283,0.01144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463853,-0.00729164) , 
9, 0.984347, 1, 0, 0.5142,-0.000169118) , 
6, 487.715, 1, 0, 0.502855,0.000468118)    );
  // itree = 182
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358673,-0.0239207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.949475,0.00580608) , 
3, 5.38479, 1, 0, 0.563781,-0.00597031) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385031,-0.00539575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531573,0.0383349) , 
6, 2252.11, 1, 0, 0.41653,0.0013941) , 
9, 1.30692, 1, 0, 0.495352,-0.00254803)    );
  // itree = 183
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629636,-0.0347087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497708,0.0212308) , 
12, 1.12511, 1, 0, 0.588679,-0.00534177) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667677,-0.00278913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232313,0.022921) , 
0, 0.693333, 1, 0, 0.467645,0.00207028) , 
9, 0.832693, 1, 0, 0.501256,1.19921e-05)    );
  // itree = 184
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.832609,0.0128132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418151,-0.0379277) , 
0, 0.457062, 1, 0, 0.61335,-0.00474689) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437072,0.0189784) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.530872,0.000569643) , 
6, 1765.92, 1, 0, 0.47411,0.00364507) , 
11, -0.695278, 1, 0, 0.499272,0.00212856)    );
  // itree = 185
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.87543,0.0283191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475031,-0.0429251) , 
0, 0.264132, 1, 0, 0.613878,-0.00675666) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29029,0.000411883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.748786,0.0243749) , 
4, 965.077, 1, 0, 0.480488,0.00324252) , 
8, -0.519319, 1, 0, 0.503984,0.0014812)    );
  // itree = 186
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507219,-0.00395649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24433,0.0293131) , 
8, 0.180556, 1, 0, 0.46721,8.16883e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.782629,0.00350025) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505824,0.0749847) , 
0, 0.834621, 1, 0, 0.705593,0.00936856) , 
5, 937.948, 1, 0, 0.505395,0.00156928)    );
  // itree = 187
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652262,0.0286149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515701,-0.00898862) , 
12, 0.932367, 1, 0, 0.592183,0.00396876) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.237503,0.00733629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512777,-0.0166285) , 
5, 264.104, 1, 0, 0.436053,-0.00327087) , 
9, 1.072, 1, 0, 0.498258,-0.000386508)    );
  // itree = 188
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531734,-0.0255333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.985167,0.0468058) , 
3, 3.89801, 1, 0, 0.774783,-0.00445524) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452087,0.0221544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227084,-0.011134) , 
8, 0.0127448, 1, 0, 0.378123,0.0040386) , 
0, 0.273872, 1, 0, 0.502436,0.00137665)    );
  // itree = 189
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621629,0.0200459) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615892,-0.0303022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441051,-0.00338005) , 
8, -0.316027, 1, 0, 0.488938,-0.00340317) , 
8, -0.71747, 1, 0, 0.499989,-0.0025787)    );
  // itree = 190
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643755,-0.0258212) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415494,0.0199133) , 
8, 0.114388, 1, 0, 0.600607,-0.00561903) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632437,0.0210984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.171989,-0.0172022) , 
0, 0.884609, 1, 0, 0.414961,0.00213677) , 
1, -0.351846, 1, 0, 0.504567,-0.00160673)    );
  // itree = 191
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610076,0.0438192) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526224,-0.000845784) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.22827,-0.0422645) , 
1, 1.24403, 1, 0, 0.491166,-0.00148099) , 
12, -0.35839, 1, 0, 0.497667,-0.00056522)    );
  // itree = 192
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57707,-0.00863181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379672,0.0183019) , 
12, 1.3311, 1, 0, 0.538633,-0.00118016) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523735,0.0911534) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.116888,-0.00613923) , 
0, 0.978783, 1, 0, 0.254323,0.0107299) , 
1, 1.17891, 1, 0, 0.502942,0.000315005)    );
  // itree = 193
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0342218,0.00541496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132612,0.0721681) , 
3, -0.9871, 1, 0, 0.0507891,0.00481595) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631306,0.000463136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.790923,-0.0362825) , 
5, 937.982, 1, 0, 0.660645,-0.0019984) , 
3, -0.553205, 1, 0, 0.496153,-0.000160423)    );
  // itree = 194
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0223732,0.0650143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391714,-0.0511641) , 
3, -0.192178, 1, 0, 0.217886,-0.00856382) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.826913,0.0326284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435947,0.00217175) , 
0, 0.075859, 1, 0, 0.525603,0.00305665) , 
7, -1.21854, 1, 0, 0.495431,0.00191723)    );
  // itree = 195
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508032,0.0221272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.568991,0.00470499) , 
6, 1261.48, 1, 0, 0.548445,0.0035061) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429104,-0.012037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.158385,-0.0802395) , 
11, -0.135659, 1, 0, 0.353659,-0.0078298) , 
12, 1.30577, 1, 0, 0.50657,0.00106908)    );
  // itree = 196
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.24817,0.0232512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492847,-0.0134873) , 
10, -1.43864, 1, 0, 0.462028,-0.0029074) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649972,0.0603848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.925595,0.0113118) , 
4, 1025.52, 1, 0, 0.796226,0.0110308) , 
10, -0.0579643, 1, 0, 0.496287,-0.00147858)    );
  // itree = 197
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566345,-0.0301662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485386,0.0106122) , 
11, -0.903404, 1, 0, 0.492079,0.00216395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.637604,-0.0329113) , 
7, 0.312437, 1, 0, 0.502118,0.00134219)    );
  // itree = 198
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541188,0.00302541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268719,-0.0282768) , 
1, 0.775807, 1, 0, 0.484176,-0.00071329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.671001,0.0357249) , 
6, 3091.5, 1, 0, 0.500143,0.000392318)    );
  // itree = 199
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499781,0.0315321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.109585,0.00102102) , 
0, 0.600117, 1, 0, 0.269457,0.00611513) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677552,0.0189498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538367,-0.015418) , 
11, -0.761115, 1, 0, 0.558511,-0.00307268) , 
10, -1.15212, 1, 0, 0.501881,-0.00127267)    );
   return;
};
 
// Clean up
inline void ReadBDTG_MaxDepth2::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG_MaxDepth2::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
